name: PointingStick
version: '${version}'
main: com.example.pointingstick.PointingStick
api-version: '1.20'
description: A plugin that allows players to point out locations.

commands:
  pointingstick:
    description: Gives you the Pointing Stick.
    usage: /<command>
    permission: pointingstick.use

permissions:
  pointingstick.use:
    description: Allows you to use the Pointing Stick.
    default: true

